### ISSUE TITLE
Jackson Serialization fails on 2.2

### ISSUE THREAD

**Issue by fref** [unitsofmeasurement/uom-lib#80]
```
java.lang.NoSuchFieldException: DEKA
	at java.base/java.lang.Class.getField(Class.java:1999)
	at tech.units.indriya.format.SymbolMap.<init>(SymbolMap.java:117)
	at tech.units.indriya.format.SymbolMap.of(SymbolMap.java:143)
	at systems.uom.ucum.format.UCUMFormat$Parsing.<clinit>(UCUMFormat.java:432)
	at systems.uom.ucum.format.UCUMFormat.getInstance(UCUMFormat.java:110)
	at tech.uom.lib.jackson.UnitJacksonModule$UnitJsonSerializer.serialize(UnitJacksonModule.java:128)
	at tech.uom.lib.jackson.UnitJacksonModule$UnitJsonSerializer.serialize(UnitJacksonModule.java:105)
```

this comes from (javax.measure.MetricPrefix from unit-api-2.2)
```
    /**
     * US alias for <code>DECA</code>.
     *
     * @param <Q>
     *          type of the quantity measured by the unit.
     * @param unit
     *          any unit.
     * @return <code>unit.times(1e1)</code>.
     * @see #DECA
     */
    public static <Q extends Quantity<Q>> Unit<Q> DEKA(Unit<Q> unit) {
        return unit.prefix(DECA);
    }
```

**Comment by keilw** [comment]
This needs [uom-systems #200](https://github.com/unitsofmeasurement/uom-systems/issues/200) to be done first. As there are no other critical issues in the 2.2 milestone, it should be possible to release it relatively soon, but please give it a few more days. Then the Jackson library also needs a 2.2 based on the 2.2 stack.
In the meantime, please use **2.2-SNAPSHOT** of `uom-lib-jackson` from the snapshot repository.

**Comment by fref** [comment]
Ok. Anything I can do to help?

**Comment by hypersonik** [comment]
> This needs [uom-systems #200](https://github.com/unitsofmeasurement/uom-systems/issues/200) to be done first. As there are no other critical issues in the 2.2 milestone, it should be possible to release it relatively soon, but please give it a few more days. Then the Jackson library also needs a 2.2 based on the 2.2 stack. In the meantime, please use **2.2-SNAPSHOT** of `uom-lib-jackson` from the snapshot repository. The latest snapshot builds already use the 2.2 final API and RI.

Where can I find the snapshot?, it is not available in maven repository, AFAIK.
I don't want to rush you, please take your time, but if there is a snapshot elsewhere I'd like to use it meanwhile.

**Comment by keilw** [comment]
It is available in its own SNAPSHOT Repository:
```
<repository>
      <snapshots>
           <enabled>true</enabled>
       </snapshots>
       <id>ossrh-snapshot</id>
       <name>OSSRH Snapshots</name>
       <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
</repository>
```
You have to add that to your POM.

**Comment by lucasvc** [comment]
> This needs [uom-systems #200](https://github.com/unitsofmeasurement/uom-systems/issues/200) to be done first. As there are no other critical issues in the 2.2 milestone, it should be possible to release it relatively soon, but please give it a few more days. Then the Jackson library also needs a 2.2 based on the 2.2 stack. In the meantime, please use **2.2-SNAPSHOT** of `uom-lib-jackson` from the snapshot repository. The latest snapshot builds already use the 2.2 final API and RI.

Has been a year, would be possible to do the milestone release?
Thanks.

**Comment by keilw** [comment]
The issue [uom-systems #200](https://github.com/unitsofmeasurement/uom-systems/issues/200) still looks open, but hope we can deal with it soon. As the active ressources are a bit small, help is always appreciated.

**Comment by keilw** [comment]
There have been issues with MavenCentral, but we can deploy there again.
Hopefully that'll get SI Units first released. After that UOM-Systems can follow, and then a new release of uom-libs like Jackson will be possible.

**Comment by lucasvc** [comment]
> The issue [uom-systems #200](https://github.com/unitsofmeasurement/uom-systems/issues/200) is still open, but hope we can deal with it soon. As the active ressources are a bit small, help is always appreciated.

Oh sorry, I wrongly understood that this issue could be _solved_ without the other one.

Thanks for taking care anyway <3

**Comment by fref** [comment]
unitsofmeasurement/uom-systems#200 is about the SI QUETTA, RONNA, QUECTO, RONTO,

but this is about the fact that in the resource bundle of UCUM, we have:
javax.measure.MetricPrefix.DEKA          = da

DEKA, documented as a US alias of DECA, in javax.measure.MetricPrefix is a method, but not an enum value

**Comment by keilw** [comment]
Yes, that will be changed with 2.2.
`DEKA` is an alias method, but we do not want to pollute or confuse the number of prefixes by keeping it as an `enum`.

**Comment by lucasvc** [comment]
Sorry @keilw to ask again, as far as I understand from tickets / artifacts found on Maven, everything is released **except** the `tech.uom.lib:uom-lib-jackson` library, which [last version found is 2.1](https://central.sonatype.com/artifact/tech.uom.lib/uom-lib-jackson). Or did I undertsood something wrong again?
Thanks.

**Comment by keilw** [comment]
@lucasvc You're right, that is a bit of a "chicken and egg" problem, since uom-lib-common is used by new versions of the RI and related libraries, while the JSON libraries use the extended and more powerful parsing of the UCUM library.
While unit-systems 2.2 had already got the new prefixes, there are a few things we tied up with 2.2.1, so as version 2.2 of the Jackson lib has not been released, we will release it based on systems 2.2.1. And especially include #82.
